### ISSUE TITLE
可以考虑让脚本更通用

### ISSUE THREAD

**Issue by enpitsuLin** [lilei2603/bilibili-follow#3]
😀还有这样的用户脚本，我马上使用，但是感觉是不是可以增加设置让用户自行设置添加某个uid的up主到首页然后变成一个更通用的脚本

**Comment by lilei2603** [comment]
后续会有这计划😄

**Comment by lilei2603** [comment]
> 😀还有这样的用户脚本，我马上使用，但是感觉是不是可以增加设置让用户自行设置添加某个uid的up主到首页然后变成一个更通用的脚本

你要的功能已经更新了。
